GoldenMorningStore/GoldenMorningStore

apis/config/auth.js, apis/config/database.js, apis/controllers/cartCtrl.js, routes.js, server.js
added config folder to hold auth keys and database setup info
setup basic server/database
configured routes.js
created a test route to show the flow w/routes.js
watched the surprise birthday video again
=> set up a few backend files

package.json
npm init
created pacakge.json
set the git hub repo to GoldenMorningStore/GoldenMorningStore
smith's has bomb bacon at the butcher
=> npm init, created pacakge.json, ghrepo GSM/GSM

package.json
installed all current dependencies and saved them into the package with --save.  
package is now ready to install dependencies with 'npm install'
=> installed the server.js files current dependencies

public/index.html
=> added materialize scripts

apis/models/cartSchema.js, apis/models/orderSchema.js, apis/models/productsSchema.js, public/scripts/app.js
added schemas into:
userSchema
cartSchema
productSchema
=> added the schemas from peter

apis/controllers/productsCtrl.js, public/scripts/views/admin/product/productCtrl.js, public/scripts/views/admin/product/productService.js, public/scripts/views/admin/product/productTmpl.html, routes.js, server.js
working on mongo. Not complete but  close
=> working on mongo

apis/models/productsSchema.js, apis/models/userSchema.js
Added userSchema and set up export to productSchema in apis/models
=> added the userSchema and added module.export to productSchema

public/index.html, public/scripts/app.js, public/scripts/services/AdminServices.js, public/scripts/views/admin/adminHome/adminHomeCtrl.js, public/scripts/views/admin/adminHome/adminHomeTmpl.html
added public/scripts/services.AdminServices.js
tied front end view to backend database via HTTP req from AdminServices.getAdminProducts
made response available by calling AdminServices.getAdminProducts() from 'admin/home' resolve in           *app.js
=> get products from DB, display on adminProductsTmpl

public/index.html, public/scripts/app.js, public/scripts/services/AdminService.js, public/scripts/services/ProductService.js, public/scripts/views/admin/adminHome/adminHomeCtrl.js, public/scripts/views/admin/adminHome/adminHomeTmpl.html, public/scripts/views/admin/product/productCtrl.js, public/scripts/views/admin/product/productService.js
moved addProduct getProduct updateProduct and deleteProduct into ProductService
refactd ../admin/product/productCtrl.js to look for ProductService not productService
refactd ../admin/adminHomeCtrl.js to look for ProductService not AdminService
refactd adminHome route in app.js to look for ProductService not AdminService
=> refactor ../admin/product/productService into ..scripts/services/ProductService

apis/models/productsSchema.js, public/scripts/views/admin/product/colorSize.js, public/scripts/views/admin/product/product.js, public/scripts/views/admin/product/productTmpl.html
Added a feature image on the product schema, product html template, and the product object.
=> added a feature image area

apis/controllers/productsCtrl.js, public/index.html, public/scripts/app.js, public/scripts/services/ProductService.js, public/scripts/views/admin/adminHome/adminHomeTmpl.html, public/scripts/views/admin/product/productCtrl.js, public/scripts/views/admin/product/updateProductCtrl.js, public/scripts/views/admin/product/updateProductTmpl.html, routes.js
can click an image in the admin/home page to bring up updateProductTmpl (based off tylers productTmpl) with the info passed in
DO NOT HAVE PUT FUNCTION WORKING
=> added updateProductTmpl and updateProductCtrl

apis/controllers/productsCtrl.js, public/scripts/services/ProductService.js
can now update entire product from admin/product/:productId >^.^<
=> got put for updateProduct working XDXD

public/scripts/views/admin/adminHome/adminHomeTmpl.html, public/scripts/views/admin/product/updateProductCtrl.js, public/scripts/views/admin/product/updateProductTmpl.html
styled after alicia's "homeTmpl"
got add/remove colorSize working
=> adminHomeTmpl

public/css/styles.css, public/scripts/views/user/home/homeCtrl.js, public/scripts/views/user/home/homeTmpl.html
=> bag modal works

public/scripts/views/admin/product/updateProductCtrl.js, public/scripts/views/admin/product/updateProductTmpl.html
changed updateProductsCtrl.js
--updateProducts will now post and get images from s3
=> fixed file upload in updateProducts

public/scripts/services/ProductService.js, public/scripts/views/admin/adminHome/adminHomeCtrl.js, public/scripts/views/admin/adminHome/adminHomeTmpl.html, public/scripts/views/admin/product/productCtrl.js, public/scripts/views/admin/product/updateProductTmpl.html
can delete specific product (after confirmation)
add/update product brings you to admin/home
can get to add product view from admin/home and admin/product/SPECIFICPRODUCT
=> delete products / tied together the admin views

public/scripts/views/admin/adminHome/adminHomeCtrl.js, public/scripts/views/admin/adminHome/adminHomeTmpl.html
added buttons to confirm or cancel deleting product from admin/home
=> can now confirm or cancel delete with separate buttons

apis/controllers/cartCtrl.js, public/scripts/services/services.js, public/scripts/views/user/home/homeCtrl.js
=> removeProductFromCart function working

apis/controllers/productsCtrl.js, public/scripts/services/ProductService.js, public/scripts/services/services.js, public/scripts/views/admin/adminHome/adminHomeCtrl.js, public/scripts/views/admin/product/updateProductCtrl.js, public/scripts/views/user/checkout/checkoutCtrl.js, public/scripts/views/user/checkout/checkoutTmpl.html, public/scripts/views/user/home/homeCtrl.js, public/scripts/views/user/home/homeTmpl.html, routes.js
can now dec an individual product's size(s) via decrement size button in shopping cart modal.
functionality is in ProductService.js and can be added to checkout function, regardless of where that will be
so stoked
=> added decrement function

public/css/styles.css, public/scripts/views/admin/adminHome/adminHomeTmpl.html
basic style on remove products from admin/home
=> styled buttons to remove product in admin/home

public/css/styles.css, public/js/init.js, public/scripts/views/admin/adminHome/adminHomeTmpl.html, public/scripts/views/admin/login/adminLogin.html, public/scripts/views/admin/product/productTmpl.html, public/scripts/views/user/home/homeTmpl.html
animationssss
add product page styled and animated
=> add product page styled-add animations

public/css/styles.css, public/scripts/app.js, public/scripts/views/admin/adminHome/adminHomeCtrl.js, public/scripts/views/admin/adminHome/adminHomeTmpl.html, public/scripts/views/admin/orders/ordersTmpl.html, views/login.ejs
styled login page
tweeked remove emails from waitlist
=> styled login page, retweeked remove emails from waitlist
